// <auto-generated />
using System;
using Medolai.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Medolai.Database.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GtdXmlEf.Models.GtdT1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Field10")
                        .HasColumnType("integer")
                        .HasColumnName("P10T1");

                    b.Property<decimal?>("Field115")
                        .HasColumnType("numeric")
                        .HasColumnName("P115T1");

                    b.Property<string>("Field12")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P12T1");

                    b.Property<string>("Field14")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("P14T1");

                    b.Property<int?>("Field17")
                        .HasColumnType("integer")
                        .HasColumnName("P17T1");

                    b.Property<decimal?>("Field18")
                        .HasColumnType("numeric")
                        .HasColumnName("P18T1");

                    b.Property<int?>("Field19")
                        .HasColumnType("integer")
                        .HasColumnName("P19T1");

                    b.Property<string>("Field2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P2T1");

                    b.Property<string>("Field21")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P21T1");

                    b.Property<string>("Field22")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P22T1");

                    b.Property<int?>("Field221")
                        .HasColumnType("integer")
                        .HasColumnName("P221T1");

                    b.Property<int?>("Field222")
                        .HasColumnType("integer")
                        .HasColumnName("P222T1");

                    b.Property<string>("Field23")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("P23T1");

                    b.Property<int?>("Field240")
                        .HasColumnType("integer")
                        .HasColumnName("P240T1");

                    b.Property<string>("Field244")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P244T1");

                    b.Property<int?>("Field25")
                        .HasColumnType("integer")
                        .HasColumnName("P25T1");

                    b.Property<int?>("Field26")
                        .HasColumnType("integer")
                        .HasColumnName("P26T1");

                    b.Property<int?>("Field27")
                        .HasColumnType("integer")
                        .HasColumnName("P27T1");

                    b.Property<int?>("Field29")
                        .HasColumnType("integer")
                        .HasColumnName("P29T1");

                    b.Property<string>("Field3")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P3T1");

                    b.Property<string>("Field30")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("P30T1");

                    b.Property<int?>("Field31")
                        .HasColumnType("integer")
                        .HasColumnName("P31T1");

                    b.Property<string>("Field32")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("P32T1");

                    b.Property<decimal?>("Field37")
                        .HasColumnType("numeric")
                        .HasColumnName("P37T1");

                    b.Property<int?>("Field38")
                        .HasColumnType("integer")
                        .HasColumnName("P38T1");

                    b.Property<string>("Field39")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("P39T1");

                    b.Property<int?>("Field4")
                        .HasColumnType("integer")
                        .HasColumnName("P4T1");

                    b.Property<string>("Field40")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("P40T1");

                    b.Property<int?>("Field41")
                        .HasColumnType("integer")
                        .HasColumnName("P41T1");

                    b.Property<int?>("Field42")
                        .HasColumnType("integer")
                        .HasColumnName("P42T1");

                    b.Property<string>("Field44")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("P44T1");

                    b.Property<int?>("Field48")
                        .HasColumnType("integer")
                        .HasColumnName("P48T1");

                    b.Property<int?>("Field5")
                        .HasColumnType("integer")
                        .HasColumnName("P5T1");

                    b.Property<int?>("Field53")
                        .HasColumnType("integer")
                        .HasColumnName("P53T1");

                    b.Property<string>("Field57")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P57T1");

                    b.Property<decimal?>("Field58")
                        .HasColumnType("numeric")
                        .HasColumnName("P58T1");

                    b.Property<decimal?>("Field59")
                        .HasColumnType("numeric")
                        .HasColumnName("P59T1");

                    b.Property<string>("Field6")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("P6T1");

                    b.Property<int?>("Field61")
                        .HasColumnType("integer")
                        .HasColumnName("P61T1");

                    b.Property<int?>("Field63")
                        .HasColumnType("integer")
                        .HasColumnName("P63T1");

                    b.Property<int?>("Field64")
                        .HasColumnType("integer")
                        .HasColumnName("P64T1");

                    b.Property<int?>("Field67")
                        .HasColumnType("integer")
                        .HasColumnName("P67T1");

                    b.Property<string>("Field7")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("P7T1");

                    b.Property<string>("Field8")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P8T1");

                    b.Property<string>("Field87")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P87T1");

                    b.Property<int?>("Field96")
                        .HasColumnType("integer")
                        .HasColumnName("P96T1");

                    b.Property<int?>("Field97")
                        .HasColumnType("integer")
                        .HasColumnName("P97T1");

                    b.Property<string>("Field98")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P98T1");

                    b.Property<string>("Field99")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P99T1");

                    b.Property<string>("ImporterEmail")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("P_IMPORTER_EMAIL");

                    b.Property<string>("ImporterPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P_IMPORTER_PHONE");

                    b.HasKey("Id")
                        .HasName("pk_t1");

                    b.ToTable("T1");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Field10")
                        .HasColumnType("integer")
                        .HasColumnName("P10T2");

                    b.Property<decimal?>("Field11")
                        .HasColumnType("numeric")
                        .HasColumnName("P11T2");

                    b.Property<int?>("Field13")
                        .HasColumnType("integer")
                        .HasColumnName("P13T2");

                    b.Property<string>("Field16")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P16T2");

                    b.Property<string>("Field17")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P17T2");

                    b.Property<decimal?>("Field18")
                        .HasColumnType("numeric")
                        .HasColumnName("P18T2");

                    b.Property<decimal?>("Field21")
                        .HasColumnType("numeric")
                        .HasColumnName("P21T2");

                    b.Property<string>("Field213")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P213T2");

                    b.Property<string>("Field214")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P214T2");

                    b.Property<decimal?>("Field22")
                        .HasColumnType("numeric")
                        .HasColumnName("P22T2");

                    b.Property<int?>("Field23")
                        .HasColumnType("integer")
                        .HasColumnName("P23T2");

                    b.Property<decimal?>("Field25")
                        .HasColumnType("numeric")
                        .HasColumnName("P25T2");

                    b.Property<decimal?>("Field26")
                        .HasColumnType("numeric")
                        .HasColumnName("P26T2");

                    b.Property<int?>("Field3")
                        .HasColumnType("integer")
                        .HasColumnName("P3T2");

                    b.Property<string>("Field30")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P30T2");

                    b.Property<decimal?>("Field37")
                        .HasColumnType("numeric")
                        .HasColumnName("P37T2");

                    b.Property<string>("Field4")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("P4T2");

                    b.Property<int?>("Field5")
                        .HasColumnType("integer")
                        .HasColumnName("P5T2");

                    b.Property<int?>("Field8")
                        .HasColumnType("integer")
                        .HasColumnName("P8T2");

                    b.Property<long?>("Field9")
                        .HasColumnType("bigint")
                        .HasColumnName("P9T2");

                    b.Property<long>("T1Id")
                        .HasColumnType("bigint")
                        .HasColumnName("T1_ID");

                    b.HasKey("Id")
                        .HasName("pk_t2");

                    b.HasIndex("T1Id")
                        .HasDatabaseName("ix_t2_t1_id");

                    b.ToTable("T2");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT4", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Field3")
                        .HasColumnType("integer")
                        .HasColumnName("P3T4");

                    b.Property<decimal?>("Field4")
                        .HasColumnType("numeric")
                        .HasColumnName("P4T4");

                    b.Property<decimal?>("Field5")
                        .HasColumnType("numeric")
                        .HasColumnName("P5T4");

                    b.Property<decimal?>("Field6")
                        .HasColumnType("numeric")
                        .HasColumnName("P6T4");

                    b.Property<int?>("Field7")
                        .HasColumnType("integer")
                        .HasColumnName("P7T4");

                    b.Property<string>("Field8")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P8T4");

                    b.Property<decimal?>("Field9")
                        .HasColumnType("numeric")
                        .HasColumnName("P9T4");

                    b.Property<long>("T2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("T2_ID");

                    b.HasKey("Id")
                        .HasName("pk_t4");

                    b.HasIndex("T2Id")
                        .HasDatabaseName("ix_t4_t2_id");

                    b.ToTable("T4");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT7", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Field3")
                        .HasColumnType("integer")
                        .HasColumnName("P3T7");

                    b.Property<string>("Field4")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("P4T7");

                    b.Property<decimal?>("Field5")
                        .HasColumnType("numeric")
                        .HasColumnName("P5T7");

                    b.Property<long>("T2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("T2_ID");

                    b.HasKey("Id")
                        .HasName("pk_t7");

                    b.HasIndex("T2Id")
                        .HasDatabaseName("ix_t7_t2_id");

                    b.ToTable("T7");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT9", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Field12")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("P12T9");

                    b.Property<string>("Field200")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P200T9");

                    b.Property<string>("Field4")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P4T9");

                    b.Property<string>("Field6")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P6T9");

                    b.Property<string>("Field7")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("P7T9");

                    b.Property<DateTime?>("Field8")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("P8T9");

                    b.Property<long>("T2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("T2_ID");

                    b.HasKey("Id")
                        .HasName("pk_t9");

                    b.HasIndex("T2Id")
                        .HasDatabaseName("ix_t9_t2_id");

                    b.ToTable("T9");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT2", b =>
                {
                    b.HasOne("GtdXmlEf.Models.GtdT1", "T1")
                        .WithMany("T2Rows")
                        .HasForeignKey("T1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_t2_t1_t1_id");

                    b.Navigation("T1");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT4", b =>
                {
                    b.HasOne("GtdXmlEf.Models.GtdT2", "T2")
                        .WithMany("T4Rows")
                        .HasForeignKey("T2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_t4_t2_t2_id");

                    b.Navigation("T2");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT7", b =>
                {
                    b.HasOne("GtdXmlEf.Models.GtdT2", "T2")
                        .WithMany("T7Rows")
                        .HasForeignKey("T2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_t7_t2_t2_id");

                    b.Navigation("T2");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT9", b =>
                {
                    b.HasOne("GtdXmlEf.Models.GtdT2", "T2")
                        .WithMany("T9Rows")
                        .HasForeignKey("T2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_t9_t2_t2_id");

                    b.Navigation("T2");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT1", b =>
                {
                    b.Navigation("T2Rows");
                });

            modelBuilder.Entity("GtdXmlEf.Models.GtdT2", b =>
                {
                    b.Navigation("T4Rows");

                    b.Navigation("T7Rows");

                    b.Navigation("T9Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
